### PR TITLE
fixes #107 -  Enable further customization of the CustomTypeProvider

### LINKED ISSUE #107: Enable further customization of the CustomTypeProvider
Adjust the output of the generated CustomTypeProvider.cs class in the following way:
- make the `_codenames` dictionary `protected`
- make the `GetType` and `GetCodename` methods virtual

### PR DESCRIPTION
**Pull request by Sevitas**
### Motivation
Enables further customization of the CustomTypeProvider

Fixes #107 

### Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [x] Tests are passing
- [ ] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test
Check whether generated CustomTypeProvider contains:
1. _GetType_ and _GetCodename_ methods are marked as **virtual**
2. __codenames_ dictionary is marked as **protected**
3. valid C# code

### CODE REVIEW

**Comment by MiroKentico** [comment]
From my point of view it is correct.

**Review by Simply007 — APPROVED** [review]
Code is ok. Just one note - I have adjusted the description so that when the pull request is merged the linked issue is closed as well:
* https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

I have one question though - where you would add the information about the extensibility of the type provider? I would put the main information into Delivery SDK Wiki - probably this section: https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Working-with-strongly-typed-models#generating-custom-type-providers and then just add a note to the kontent-generators-net Readme file - @Sevitas @MiroKentico what do you think?

**Comment by Sevitas** [comment]
> ity of the type provider? I would put the main information into Delivery SDK Wiki - probably this sec

It makes sense to put it into wiki and link it to the readme.

**Comment by Sevitas** [comment]
updated [readme](https://github.com/Kentico/kontent-generators-net/commit/bda2a5e41a35f7f926e481bb84286e20e8933bd4)
updated [documentation](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Working-with-strongly-typed-models/_compare/a3c8b8ad48201f346807acce180bd5954356014f...c64ad99dd2c325a911617e3ad31a34269673b527)
@Simply007

**Comment by Simply007** [comment]
> updated [readme](https://github.com/Kentico/kontent-generators-net/commit/bda2a5e41a35f7f926e481bb84286e20e8933bd4)
> updated [documentation](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Working-with-strongly-typed-models/_compare/a3c8b8ad48201f346807acce180bd5954356014f...c64ad99dd2c325a911617e3ad31a34269673b527)
> @Simply007

I have reverted the readme change - https://github.com/Kentico/kontent-generators-net/commit/31e02dd4310e70c402a6d631fb40287aa5b2005b + just adjusted link to wiki - I guess it is fine, we don!t want the same information on two places.

Rephrase in the wiki page to make it a bit more maintainable: https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Working-with-strongly-typed-models/_compare/c64ad99dd2c325a911617e3ad31a34269673b527...c0e09400372dc4e248e61fd25a5e113bfc3074e8

**Comment by Sevitas** [comment]
I've found another place [link](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Strong-Types-Explained-%E2%80%93-Code-Generator#the-type-provider) which might be edited (codesnippet). @Simply007 what do you think?

**Comment by Simply007** [comment]
> I've found another place [link](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Strong-Types-Explained-%E2%80%93-Code-Generator#the-type-provider) which might be edited (codesnippet). @Simply007 what do you think?

Make sence to me. Let's add it.

**Comment by Sevitas** [comment]
> > I've found another place [link](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Strong-Types-Explained-%E2%80%93-Code-Generator#the-type-provider) which might be edited (codesnippet). @Simply007 what do you think?
> 
> Make sence to me. Let's add it.

https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Strong-Types-Explained-%E2%80%93-Code-Generator/_compare/27937f5138305cfbe8516eb7ee77927710614907...ff2584666e02a860e0d475ba822ec738cba89aba

**Comment by Simply007** [comment]
Cool, let's merge it - @Sevitas - will you do the donors?

**Pull request merged**
